# Generated by Django 5.1.1 on 2024-09-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tasks_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority_task',
            field=models.CharField(choices=[('1', 'Baixa'), ('2', 'Média'), ('3', 'Alta')], default='1', max_length=10),
        ),
    ]
