# Generated by Django 5.1.1 on 2024-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('title_task', models.CharField(max_length=200)),
                ('description_task', models.TextField()),
                ('complete_task', models.BooleanField(default=False)),
                ('created_task', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
