# Generated by Django 5.1.1 on 2024-09-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_created_task_tasks_prazo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority_task',
            field=models.CharField(choices=[('3', 'Alta'), ('2', 'Média'), ('1', 'Baixa')], default='1', max_length=10),
        ),
    ]
