# Generated by Django 5.1.1 on 2024-09-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tasks_priority_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='prazo_task',
            field=models.DateTimeField(),
        ),
    ]
