# Generated by Django 5.1.1 on 2024-09-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_tasks_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='complete_task',
            field=models.CharField(choices=[('1', 'Pendente'), ('2', 'Em andamento'), ('3', 'Concluída')], default='1', max_length=10),
        ),
    ]
